import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>
          <Link href="/">Home Page</Link>
        </h1>
        <nav>
          <ul>
            <li>
              <Link href="/project">PROJECT</Link>
            </li>
            <li>
              <Link href="/project/art">ART</Link>
            </li>
            <li>
              <Link href="/user_info">ユーザー情報登録ページ</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
